sudo: required

language: minimal

services:
  - docker

matrix:
  include:
  - name: "debian"
    env:
      DOCKER_BUILD=domoticz:debian
      DOCKER_PATH=.
  - name: "alpine"
    env:
      DOCKER_BUILD=domoticz:alpine
      DOCKER_PATH=alpine
  - name: "debian-easy"
    env:
      DOCKER_BUILD=domoticz:debian-easy
      DOCKER_PATH=debian-easy
  - name: "debian-beta"
    env:
      DOCKER_BUILD=domoticz:debian-beta
      DOCKER_PATH=debian-beta
  - name: "alpine-pkg"
    env:
      DOCKER_BUILD=domoticz:alpine-pkg
      DOCKER_PATH=alpine-pkg

install:
  - docker build -t ${DOCKER_BUILD} -f ${DOCKER_PATH}/Dockerfile ${DOCKER_PATH}
  - docker run -d --name=domoticz -p 8080:8080 ${DOCKER_BUILD}

before_script:
  - sleep 60

script:
  - docker ps | grep ${DOCKER_BUILD}
  - curl -f "http://127.0.0.1:8080/json.htm?type=command&param=getversion"
