sudo: required

language: cpp

services:
  - docker

env:
  matrix:
    - name: "latest"
      DOCKER_BUILD=domoticz:latest
      DOCKERFILE=Dockerfile
    - name: "alpine"
      DOCKER_BUILD=domoticz:alpine
      DOCKERFILE=Dockerfile.alpine
      
install:
  - docker build -t ${DOCKER_BUILD} -f ${DOCKERFILE} .
  - docker run -d --name=domoticz -p 8080:8080 ${DOCKER_BUILD}

postinstall:
  - sleep 120

script:
  - docker ps | grep domoticz
  - curl -f "http://127.0.0.1:8080/json.htm?type=command&param=getversion"
